sources:
  - Merriweather.glyphspackage
  - Merriweather-Italic.glyphspackage
axisOrder:
  - opsz 
  - wdth
  - wght

familyName: Merriweather
buildStatic: false
buildWebfont: false
buildTTF: false
buildOTF: false
buildSmallCap: true
