sources:
  - Merriweather.glyphspackage
  - Merriweather-Italic.glyphspackage
axisOrder:
  - wght
  - wdth
  - opsz

familyName: Merriweather
buildStatic: true
buildWebfont: false
buildTTF: true
buildOTF: false
buildSmallCap: false