sources:
  - Merriweather.glyphspackage
  - Merriweather-Italic.glyphspackage
axisOrder:
  - wght
  - wdth
  - opsz

familyName: Merriweather
buildStatic: false
buildWebfont: false
buildTTF: false
buildOTF: false
buildSmallCap: true

stat:
  Merriweather[opsz,wdth,wght].ttf:
  - name: Optical size
    tag: opsz
    values:
    - name: 18pt
      value: 18
    - name: 24pt
      value: 24
    - name: 36pt
      value: 36
    - name: 72pt
      value: 72
    - name: 144pt
      value: 144
  - name: Width
  tag: wdth
  values:
    - name: Cond
    value: 87
    - name: Normal
    value: 100
    - name: Wide
    value: 112
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: ExtraBold
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  Merriweather-Italic[opsz,wdth,wght].ttf:
   - name: Optical size
    tag: opsz
    values:
    - name: 18pt
      value: 18
    - name: 24pt
      value: 24
    - name: 36pt
      value: 36
    - name: 72pt
      value: 72
    - name: 144pt
      value: 144
  - name: Width
  tag: wdth
  values:
  - name: Cnd
    value: 87
    - name: Normal
    value: 100
    - name: Wide
    value: 112
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: ExtraBold
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1
  MerriweatherSC[opsz,wdth,wght].ttf:
  - name: Optical size
    tag: opsz
    values:
    - name: 18pt
      value: 18
    - name: 24pt
      value: 24
    - name: 36pt
      value: 36
    - name: 72pt
      value: 72
    - name: 144pt
      value: 144
  - name: Width
  tag: wdth
  values:
    - name: Cond
    value: 87
    - name: Normal
    value: 100
    - name: Wide
    value: 112
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: ExtraBold
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Roman
      value: 0
      linkedValue: 1
      flags: 2
  MerriweatherSC-Italic[opsz,wdth,wght].ttf:
   - name: Optical size
    tag: opsz
    values:
    - name: 18pt
      value: 18
    - name: 24pt
      value: 24
    - name: 36pt
      value: 36
    - name: 72pt
      value: 72
    - name: 144pt
      value: 144
  - name: Width
  tag: wdth
  values:
  - name: Cnd
    value: 87
    - name: Normal
    value: 100
    - name: Wide
    value: 112
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 800
    - name: ExtraBold
      value: 900
  - name: Italic
    tag: ital
    values:
    - name: Italic
      value: 1