sources:
  - Merriweather.glyphspackage
  - Merriweather-Italic.glyphspackage
axisOrder:
  - opsz 
  - wdth
  - wght

familyName: Merriweather
buildStatic: false
buildWebfont: false
buildTTF: false
buildOTF: false
buildSmallCap: true

flattenComponents: False

stat:
    Merriweather[wght].ttf:
    - name: Weight
      tag: wght
      values:
      - name: Light
        value: 300
      - name: Regular
        value: 400
        linkedValue: 700
        flags: 2
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
      - name: ExtraBold
        value: 800
      - name: Black
        value: 900
    - name: Italic
      tag: ital
      values:
      - name: Roman
        value: 0
        linkedValue: 1
        flags: 2
      - name: Width
      tag: wdth
      - name: Condensed
        value: 87
      - name: Normal
        value: 100
        flags: 2
      - name: Wide
        value: 112
      - name: Optical Size
      tag: opsz
      values:
      - name: 12
        value: 12
      - name: 14
        value: 14
      - name: 16
        value: 16
      - name: 24
        value: 24
      - name: 48
        value: 48
      - name: 64
        value: 64
      - name: 72
        value: 72
      - name: 144
        value: 144
    Merriweather-Italic[wght].ttf:
    - name: Weight
      tag: wght
      values:
      - name: Light
        value: 300
      - name: Regular
        value: 400
        linkedValue: 700
        flags: 2
      - name: Medium
        value: 500
      - name: SemiBold
        value: 600
      - name: Bold
        value: 700
      - name: ExtraBold
        value: 800
      - name: Black
        value: 900
    - name: Italic
      tag: ital
      values:
      - name: Italic
        value: 1
      - name: Width
      tag: wdth
      - name: Condensed
        value: 87
      - name: Normal
        value: 100
        flags: 2
      - name: Wide
        value: 112
      - name: Optical Size
      tag: opsz
      values:
      - name: 12
        value: 12
      - name: 14
        value: 14
      - name: 16
        value: 16
      - name: 24
        value: 24
      - name: 48
        value: 48
      - name: 64
        value: 64
      - name: 72
        value: 72
      - name: 144
        value: 144