sources:
  - Merriweather.glyphspackage
  - Merriweather-Italic.glyphspackage
axisOrder:
  - wght
  - wdth
  - opsz

stat:
  - name: Weight
    tag: wght
    values:
    - name: Light
      value: 300
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700
    - name: ExtraBold
      value: 700
    - name: Black
      value: 900
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 87
    - name: Normal
      value: 100
      flags: 2
    - name: Wide
      value: 112
  - name: Optical Size
    tag: opsz
    values:
    - name: 7
      value: 7
    - name: 12
      value: 12
    - name: 24
      value: 24
    - name: 48
      value: 48
    - name: 64
      value: 64
    - name: 72
      value: 72
    - name: 144
      value: 144

familyName: Merriweather
buildStatic: false
buildWebfont: true